name       : dnspython
version    : 1.14.0
release    : 1
source     :
    - https://github.com/rthalley/dnspython/archive/v1.14.0.tar.gz : d17a692524447d8221860de87f0417fa247840b50ea87a81dfafe402260d52f5
license    : ISC
component  : programming.python
summary    : DNS toolkit for Python
description: |
    DNS toolkit for Python supporting almost all record types. It can be used for queries, zone transfers, and dynamic updates.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install