name       : dnspython
version    : 1.16.0
release    : 6
source     :
    - https://github.com/rthalley/dnspython/archive/v1.16.0.tar.gz : b339ac2eb070d0133f020a6e0cc137a10fc380f3eba3e0655d62a19e64626cbd
license    : ISC
component  : programming.python
summary    : DNS toolkit for Python
description: |
    DNS toolkit for Python supporting almost all record types. It can be used for queries, zone transfers, and dynamic updates.
builddeps  :
    - pkgconfig(python3)
    - python-typing
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
