name       : dnspython
version    : 2.2.1
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/d/dnspython/dnspython-2.2.1.tar.gz : 0f7569a4a6ff151958b64304071d370daa3243d15941a7beedf0c9fe5105603e
homepage   : https://www.dnspython.org/
license    : ISC
component  : programming.python
summary    : DNS toolkit for Python
description: |
    DNS toolkit for Python supporting almost all record types. It can be used for queries, zone transfers, and dynamic updates.
builddeps  :
    - python-pytest # check
    - python-setuptools-scm
    - python-trio   # check
    - python-toml
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
