name       : dnspython
version    : 1.15.0
release    : 3
source     :
    - https://github.com/rthalley/dnspython/archive/v1.15.0.tar.gz : 760078a8a87d85452177a406203681aaee9bfb8cbba2843425883709cd5b2af5
license    : ISC
component  : programming.python
summary    : DNS toolkit for Python
description: |
    DNS toolkit for Python supporting almost all record types. It can be used for queries, zone transfers, and dynamic updates.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
