name       : dnspython
version    : 2.2.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/d/dnspython/dnspython-2.2.0.tar.gz : e79351e032d0b606b98d38a4b0e6e2275b31a5b85c873e587cc11b73aca026d6
homepage   : https://www.dnspython.org/
license    : ISC
component  : programming.python
summary    : DNS toolkit for Python
description: |
    DNS toolkit for Python supporting almost all record types. It can be used for queries, zone transfers, and dynamic updates.
builddeps  :
    - python-pytest # check
    - python-setuptools-scm
    - python-trio   # check
    - python-toml
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
