name       : dnspython
version    : 2.1.0
release    : 7
source     :
    - https://github.com/rthalley/dnspython/archive/refs/tags/v2.1.0.tar.gz : 7406a6f754abad3f47309d808f14d544f7e3cc50094d6232bbe1ddb1cfc408a2
homepage   : https://www.dnspython.org/
license    : ISC
component  : programming.python
summary    : DNS toolkit for Python
description: |
    DNS toolkit for Python supporting almost all record types. It can be used for queries, zone transfers, and dynamic updates.
builddeps  :
    - python-pytest
    - python-trio
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
